from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer

pdf_path = "Learning_Path_CS_ML_Robotics.pdf"
doc = SimpleDocTemplate(pdf_path, pagesize=A4)
elements = []

# Title
styles = getSampleStyleSheet()
title_style = styles['Title']
title = Paragraph("Learning Path for Computer Science, ML, Robotics & Web Development", title_style)
elements.append(title)
elements.append(Spacer(1, 12))

# Table data
table_data = [
    ["Class", "Focus"],
    ["9–10", "Learn basics of coding and robotics"],
    ["11–12", "PCM + Computer Science (if possible)"],
    ["B.Tech", "Computer Science / AI / Robotics"]
]

# Table styling
table = Table(table_data, colWidths=[70, 350])
table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.lightblue),
    ('TEXTCOLOR', (0, 0), (-1, 0), colors.darkblue),
    ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
    ('FONTSIZE', (0, 0), (-1, 0), 12),
    ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
    ('BACKGROUND', (0, 1), (-1, -1), colors.whitesmoke),
    ('GRID', (0, 0), (-1, -1), 1, colors.blue),
]))

elements.append(table)
elements.append(Spacer(1, 24))

# Footer
footer_style = ParagraphStyle(
    name='Footer',
    fontSize=8,
    alignment=1,  # Center
    textColor=colors.grey,
)
footer = Paragraph("Generated by Harnidh (ChatGPT)", footer_style)
elements.append(footer)

doc.build(elements)

pdf_path
